# Generated by Django 2.1 on 2018-09-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('psw_md5', models.CharField(max_length=32)),
                ('salt', models.CharField(max_length=6)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=11)),
            ],
        ),
    ]
