# Generated by Django 2.1 on 2018-09-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='FollowUser',
            field=models.ManyToManyField(related_name='_webuser_FollowUser_+', to='WebUser.WebUser', verbose_name='所关注用户'),
        ),
    ]
