# Generated by Django 2.1 on 2018-09-17 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebUser', '0002_webuser_followuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='sessionid',
            field=models.CharField(default=django.utils.timezone.now, max_length=43),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webuser',
            name='sessionid_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
