# Generated by Django 2.1 on 2018-09-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUser', '0003_auto_20180917_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='sessionid',
            field=models.CharField(blank=True, max_length=43),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='sessionid_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
